# Generated by Django 4.0 on 2021-12-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_blos',
            new_name='Post_blogs',
        ),
    ]
